### ISSUE TITLE
piWallet returns error: HTTP request failed! HTTP/1.1 500 Internal Server Error

### ISSUE THREAD

**Issue by BlockGardener** [johnathanmartin/piWallet#96]
I have setup piWallet on a VPS with a clone of Blackcoin.

The apache logs show the following error message when I login with the username "piWallet".

```
PHP Warning:  fopen(http://...@127.0.0.1:8737/): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error\r\n in /var/www/html/jsonRPCClient.php on line 133

PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to connect to http://rpc_examplecoin:CQRMSKLFUikEppUzKNbR7tGFKPMq3zhlS3eBUp2f@127.0.0.1:8737/' in /var/www/html/jsonRPCClient.php:141\nStack trace:\n#0 /var/www/html/classes/Client.php(17): jsonRPCClient->__call('getbalance', Array)\n#1 /var/www/html/classes/Client.php(17): jsonRPCClient->getbalance('zelles(piWallet...', 6)\n#2 /var/www/html/index.php(23): Client->getBalance('piWallet')\n#3 {main}\n  thrown in /var/www/html/jsonRPCClient.php on line 141
```

The settings file:
```
<?php

$server_url = "/";  // ENTER WEBSITE URL ALONG WITH A TRAILING SLASH

$db_host = "localhost";
$db_user = "wallet_user";
$db_pass = "Ee4cxBN6VaThkAr4fKigzWR7veDPZlvU1dVzYg4H";
$db_name = "wallet";

$rpc_host = "127.0.0.1";
$rpc_port = "8737";
$rpc_user = "rpc_examplecoin";
$rpc_pass = "CQRMSKLFUikEppUzKNbR7tGFKPMq3zhlS3eBUp2f";

$fullname = "Examplecoin"; //Website Title (Do Not include 'wallet')
$short = "EXP"; //Coin Short (BTC)
$blockchain_tx_url = "http://blockchain.info/tx/"; //Blockchain Url
$support = "support@yourwebsite.com"; //Your support eMail
$hide_ids = array(1); //Hide account from admin dashboard
$donation_address = "Ey7w8sZqnXMsjGpFejSQeYv4GWo88WvLYx"; //Donation Address

$reserve = "0"; //This fee acts as a reserve. The users balance will display as the balance in the daemon minus the reserve. We don't reccomend setting this more than the Fee the daemon charges.

```
The config file:
```
rpcuser=rpc_examplecoin
rpcpassword=CQRMSKLFUikEppUzKNbR7tGFKPMq3zhlS3eBUp2f
rpcallowip=127.0.0.1
listen=1
server=1
txindex=1
daemon=1
enableaccounts=1
```

I tested the daemon with PHP and curl, this seems to work correct.

Output of a curl request to the daemon with the command getbalance:
`{"result":0.00000000,"error":null,"id":null}`

Do you know a solution to why piWallet throws the error message "HTTP/1.1 500 Internal Server Error"?

Let me know if you require more information.

**Comment by walletbuilders** [comment]
It is required to add "staking=0" to the config file of your daemon, when using piWallet in combination with a coin that uses Proof-of-Stake (PoS).

Example config:

rpcuser=rpc_examplecoin
rpcpassword=CQRMSKLFUikEppUzKNbR7tGFKPMq3zhlS3eBUp2f
rpcallowip=127.0.0.1
listen=1
server=1
txindex=1
daemon=1
**enableaccounts=1
staking=0**

**Comment by xcelr** [comment]
Im getting the same issue, runs thru Curl fine 

`curl --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"getblockchaininfo","params":[]}' -H 'content-type:text/plain;' http://xcelr:xcelr@127.0.0.1:2049/
{"result":{"chain":"main","blocks":2284,"headers":2284,"bestblockhash":"bbf97bb5211961bdf83a47bc392fcdb9a9f15eb678643b7c1da2af021ddee74f","difficulty":0.0002699116592545264,"mediantime":1613889869,"verificationprogress":4.33103051287275e-05,"initialblockdownload":false,"chainwork":"000000000000000000000000000000000000000000000000000000009096e2a3","size_on_disk":799180,"pruned":false,"softforks":[{"id":"bip34","version":2,"reject":{"status":false}},{"id":"bip66","version":3,"reject":{"status":false}},{"id":"bip65","version":4,"reject":{"status":false}}],"bip9_softforks":{"csv":{"status":"defined","startTime":1485561600,"timeout":1517356801,"since":0},"segwit":{"status":"defined","startTime":1485561600,"timeout":1517356801,"since":0}},"warnings":""},"error":null,"id":"curltext"}`



`curl --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"getbalance","params":[]}' -H 'content-type:text/plain;' http://xcelr:xcelr@127.0.0.1:2049/
{"result":0.00000000,"error":null,"id":"curltext"}`



Conf File Setup:

addnode=164.90.130.14:2048
addnode=164.90.139.226:2048
rpcuser=xcelr
rpcpassword=xcelr
rpcallowip=127.0.0.1
rpcport=2049
addresstype=legacy
listen=0  // (This worked to get Curl running, as before it did not would "connection refuse")
server=1
txindex=1
enableaccounts=1
staking=0 // (Added this in even though my coin XcelR is POW)



==============================================================



I remember back in 2018 using PiWallet with no issues. XcelR is a fork of Litecoin v0.17 ( Originally using a fork of Litecoin 0.15. )

Would love to get this figured out.  

Willing to drop a BTC,LTC,XRP Bounty for a lead in the right direction. 

On the script itself. After Login it throws. 




`Fatal error: Uncaught exception 'Exception' with message 'Unable to connect to http://xcelr:xcelrb@127.0.0.1:2049/' in /var/www/html/jsonRPCClient.php:141 Stack trace: #0 /var/www/html/classes/Client.php(17): jsonRPCClient->__call('getbalance', Array) #1 /var/www/html/classes/Client.php(17): jsonRPCClient->getbalance('zelles(piWallet...', 6) #2 /var/www/html/index.php(22): Client->getBalance('piWallet') #3 {main} thrown in /var/www/html/jsonRPCClient.php on line 141`

`Warning: fopen(http://...@127.0.0.1:2049/): failed to open stream: HTTP request failed! HTTP/1.0 500 Internal Server Error in /var/www/html/jsonRPCClient.php on line 133`




**When i get this sorted out ill be sure to post a full update on this issue**

I'll play around with it a little more and hopefully come to a solution on my own.



Feel Free To Reach Out = xcelrproject@gmail.com
